// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7q3GZKWsvW2TbtfnBVnSdeRy-LX2b74',
    appId: '1:478826806121:web:e9b99cc69a569111461bf8',
    messagingSenderId: '478826806121',
    projectId: 'workconnect-02',
    authDomain: 'workconnect-02.firebaseapp.com',
    storageBucket: 'workconnect-02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7q3GZKWsvW2TbtfnBVnSdeRy-LX2b74',
    appId: '1:478826806121:android:e9b99cc69a569111461bf8',
    messagingSenderId: '478826806121',
    projectId: 'workconnect-02',
    authDomain: 'workconnect-02.firebaseapp.com',
    storageBucket: 'workconnect-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBqj8Avv9p0oCVGJPEifJm73U6Lljedic',
    appId: '1:478826806121:ios:3c01dd7ac9621430461bf8',
    messagingSenderId: '478826806121',
    projectId: 'workconnect-02',
    authDomain: 'workconnect-02.firebaseapp.com',
    storageBucket: 'workconnect-02.firebasestorage.app',
    iosBundleId: 'com.example.workConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY7q3GZKWsvW2TbtfnBVnSdeRy-LX2b74',
    appId: '1:478826806121:ios:e9b99cc69a569111461bf8',
    messagingSenderId: '478826806121',
    projectId: 'workconnect-02',
    authDomain: 'workconnect-02.firebaseapp.com',
    storageBucket: 'workconnect-02.firebasestorage.app',
    iosBundleId: 'com.example.workConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7q3GZKWsvW2TbtfnBVnSdeRy-LX2b74',
    appId: '1:478826806121:web:e9b99cc69a569111461bf8',
    messagingSenderId: '478826806121',
    projectId: 'workconnect-02',
    authDomain: 'workconnect-02.firebaseapp.com',
    storageBucket: 'workconnect-02.firebasestorage.app',
  );
}